# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the App Center"
  lane :release_beta do
      appcenter_upload(
        api_token: "c9f4ad7b6c584e89ae552f88fc6e318d28afbedd",
        owner_name: "humax",
        owner_type: "organization", # Default is user - set to organization for appcenter organizations
        app_name: "H-SOS-Android",
        apk: "./app/build/outputs/apk/release/app-release.apk",
        destinations: "public",
        destination_type: "group",
        release_notes: "New build version",
        notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
    end
end
